// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package spike

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TcpBytesCloseEvent struct {
	_             structs.HostLayout
	BytesSent     uint64
	BytesReceived uint64
	Saddr         [4]uint8
	Daddr         [4]uint8
	Sport         uint16
	Dport         uint16
	Pad           [4]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	TcpBytesMapActiveOpens     = "active_opens"
	TcpBytesMapCloses          = "closes"
	TcpBytesMapSpikeStats      = "spike_stats"
	TcpBytesProgTraceClose     = "trace_close"
	TcpBytesProgTraceEstablish = "trace_establish"
	TcpBytesVarUnused          = "unused"
)

// LoadTcpBytes returns the embedded CollectionSpec for TcpBytes.
func LoadTcpBytes() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpBytesBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TcpBytes: %w", err)
	}

	return spec, err
}

// LoadTcpBytesObjects loads TcpBytes and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TcpBytesObjects
//	*TcpBytesPrograms
//	*TcpBytesMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTcpBytesObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTcpBytes()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TcpBytesSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpBytesSpecs struct {
	TcpBytesProgramSpecs
	TcpBytesMapSpecs
	TcpBytesVariableSpecs
}

// TcpBytesProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpBytesProgramSpecs struct {
	TraceClose     *ebpf.ProgramSpec `ebpf:"trace_close"`
	TraceEstablish *ebpf.ProgramSpec `ebpf:"trace_establish"`
}

// TcpBytesMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpBytesMapSpecs struct {
	ActiveOpens *ebpf.MapSpec `ebpf:"active_opens"`
	Closes      *ebpf.MapSpec `ebpf:"closes"`
	SpikeStats  *ebpf.MapSpec `ebpf:"spike_stats"`
}

// TcpBytesVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpBytesVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"unused"`
}

// TcpBytesObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTcpBytesObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpBytesObjects struct {
	TcpBytesPrograms
	TcpBytesMaps
	TcpBytesVariables
}

func (o *TcpBytesObjects) Close() error {
	return _TcpBytesClose(
		&o.TcpBytesPrograms,
		&o.TcpBytesMaps,
	)
}

// TcpBytesMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTcpBytesObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpBytesMaps struct {
	ActiveOpens *ebpf.Map `ebpf:"active_opens"`
	Closes      *ebpf.Map `ebpf:"closes"`
	SpikeStats  *ebpf.Map `ebpf:"spike_stats"`
}

func (m *TcpBytesMaps) Close() error {
	return _TcpBytesClose(
		m.ActiveOpens,
		m.Closes,
		m.SpikeStats,
	)
}

// TcpBytesVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTcpBytesObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpBytesVariables struct {
	Unused *ebpf.Variable `ebpf:"unused"`
}

// TcpBytesPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTcpBytesObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpBytesPrograms struct {
	TraceClose     *ebpf.Program `ebpf:"trace_close"`
	TraceEstablish *ebpf.Program `ebpf:"trace_establish"`
}

func (p *TcpBytesPrograms) Close() error {
	return _TcpBytesClose(
		p.TraceClose,
		p.TraceEstablish,
	)
}

func _TcpBytesClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpbytes_x86_bpfel.o
var _TcpBytesBytes []byte
