// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TcpConnectEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	Pid         uint32
	Saddr       [4]uint8
	Daddr       [4]uint8
	Sport       uint16
	Dport       uint16
	Family      uint8
	Protocol    uint8
	Version     uint8
	Pad         [5]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	TcpConnectMapEvents                 = "events"
	TcpConnectMapStats                  = "stats"
	TcpConnectProgTraceInetSockSetState = "trace_inet_sock_set_state"
	TcpConnectVarUnusedEvent            = "unused_event"
)

// LoadTcpConnect returns the embedded CollectionSpec for TcpConnect.
func LoadTcpConnect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpConnectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TcpConnect: %w", err)
	}

	return spec, err
}

// LoadTcpConnectObjects loads TcpConnect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TcpConnectObjects
//	*TcpConnectPrograms
//	*TcpConnectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTcpConnectObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTcpConnect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TcpConnectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpConnectSpecs struct {
	TcpConnectProgramSpecs
	TcpConnectMapSpecs
	TcpConnectVariableSpecs
}

// TcpConnectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpConnectProgramSpecs struct {
	TraceInetSockSetState *ebpf.ProgramSpec `ebpf:"trace_inet_sock_set_state"`
}

// TcpConnectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpConnectMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
	Stats  *ebpf.MapSpec `ebpf:"stats"`
}

// TcpConnectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpConnectVariableSpecs struct {
	UnusedEvent *ebpf.VariableSpec `ebpf:"unused_event"`
}

// TcpConnectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTcpConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpConnectObjects struct {
	TcpConnectPrograms
	TcpConnectMaps
	TcpConnectVariables
}

func (o *TcpConnectObjects) Close() error {
	return _TcpConnectClose(
		&o.TcpConnectPrograms,
		&o.TcpConnectMaps,
	)
}

// TcpConnectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTcpConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpConnectMaps struct {
	Events *ebpf.Map `ebpf:"events"`
	Stats  *ebpf.Map `ebpf:"stats"`
}

func (m *TcpConnectMaps) Close() error {
	return _TcpConnectClose(
		m.Events,
		m.Stats,
	)
}

// TcpConnectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTcpConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpConnectVariables struct {
	UnusedEvent *ebpf.Variable `ebpf:"unused_event"`
}

// TcpConnectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTcpConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpConnectPrograms struct {
	TraceInetSockSetState *ebpf.Program `ebpf:"trace_inet_sock_set_state"`
}

func (p *TcpConnectPrograms) Close() error {
	return _TcpConnectClose(
		p.TraceInetSockSetState,
	)
}

func _TcpConnectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpconnect_x86_bpfel.o
var _TcpConnectBytes []byte
